### ISSUE TITLE
waitFor is different from facebook's

### ISSUE THREAD

**Issue by roganov** [r3dm/thundercats#71]
In original Flux, `waitFor` waits until stores finished processing _current_ action, while in your implementation it seems that it waits for any event. For example, a store I'm 'waiting for' might react to some asynchronous event that originated in a previous action, therefore unblocking `watiFor`.

**Comment by BerkeleyTrue** [comment]
Hey @roganov,

You are correct that waitFor listens to any update from the store passed in. One thing that may not be obvious is that Rx Observables are all synchronous by default (until 3.0 comes out...) meaning an observable will notify its observers of their payload one after the other all on the same stack and waitFor uses combineLatest under the hood and hot observables which prevents the scenario you describe above.

Lets take the flux example given [here](https://facebook.github.io/flux/docs/dispatcher.html):

We have a `countryUpdate` action and we want city store to get the default city for that country on this action.

In our city store we register the countryUpdate action with a waitFor countryStore and a map operation to `getDefaultCityForCountry`. 

``` js
// in cityStore constructor using thundercats@2.0.0-rc6
this.register(countryActions
  .countryUpdate
  // waitFor countryStore to publish new value (could be from any event)
  .waitFor(countryStore)
  .map((country) => {
    return getDefaultCityForCountry(country);
  })
);
```

Now we call the countryUpdate:

``` js
countryActions.countryUpdate({ selectedCountry: 'Australia });
```

Now internally the countryUpdate action/observable has a list of observers it needs to go through. It will notify each observable and wait for that specific chain to complete.

Lets say it first goes through the chain that notifies the cityStore first. This will prime the waitFor, which will not publish a value until countryStore publishes a value.

Now here is where control goes back to the the action observable, which then goes to the next observer in its list, which is the countryStore. Because observable actions are synchronize (which is very import for flux to work properly) Its not possible for something to happen in between the country and city stores to being updated.

Do you have some examples where the behavior above is broken? If so I will need to write some more test.

There is something that is bugging me. If the country store is the first to be notified the waitfor has not been setup and cityStore will end up waiting for the next publish from countryStore. I might need to write some test to see what the outcome would be in this situation.

**Comment by BerkeleyTrue** [comment]
@roganov After a couple of thought experiments I have come to the same conclusion you have, the current implementation is completely wrong for the intent of waitFor.

## possible solution:

actions on subscription store the observer (in most cases this is the store observing an action) in an array. 

On waitFors, what I can do is delay progression of this observable emission until that particular observer is notified.

**Comment by BerkeleyTrue** [comment]
@roganov, after discussing this in RxJS chat, it seems like waitFor may be unnecessary when there are many ways to implement the effects of waitFor.

Can you describe your use case?

What I will end up doing is moving waitFor internally and removing it from docs while adding examples of how to replace it with regular RxJs operators.

**Comment by roganov** [comment]
@BerkeleyTrue I don't actually have a use case for `waitFor`, I've been browsing different implementations of flux with Rx, saw this peculiar piece of code and decided to open an issue.
I haven't yet written a lot of code mixing Rx and React, but so far avoiding `waitFor` was easy (what I did found is that Rx lacks a clear substitute for Bacon's `toProperty`).

P.S. Could you please give the link for the RxJS chat that you mentioned?

**Comment by BerkeleyTrue** [comment]
Sure! it's https://gitter.im/Reactive-Extensions/RxJS 

I guess the solution to this issue is to completely remove waitFor from the package exposure. (maybe rename it to something else because I have found it useful for other things) and add examples to the guide that accomplish the same thing with RxJS operators.

For future readers: I have an example https://github.com/r3dm/thundercats-chat that does not use waitFor but accomplishes the same thing. 

I'll close this when I get some time to add the examples to the README
