### ISSUE TITLE
Bind Action Methods to the Stamp?

### ISSUE THREAD

**Issue by joshdmiller** [r3dm/thundercats#77]
To make actions composable, it makes sense keep the methods passed to the actions bound to the stamp. This would immediately make things like this possible:

``` js
var Logger = stampit().methods({
  log ( msg ) {
    // ...
  }
});

var TodoActions = Logger.compose(Actions({
  create ( text ) {
    this.log( `Adding todo: ${text}` );
    // ...
  }
}));
```

But I think we should also be able to do things like this:

``` js
var TodoActions = Actions({
  _log ( msg ) {
    // ...
  },

  create ( text ) {
    this._log( `Adding todo: ${text}` );
    // ...
  }
});
```

**Comment by BerkeleyTrue** [comment]
Hey @joshdmiller!

You've given me a lot to think about.

One thing to note is that what is being passed into `Actions` is not a bag of methods but should be thought of as the minimum specification of the instance to create from the resulting factory/stamp. That is why you can pass in a object with keys that have null values. It's an important difference.

The main reason it's done this way is due to the fact that Observable are themselves constructors ([ref](https://github.com/ThunderCatsJS/thundercats/blob/master/src/Actions.js#L68)), so the action methods need to be instantiated during Actions object (which is really more of a name space then anything) instantiation. 

so this:

``` js
var TodoActions = Actions({
  _log ( msg ) {
    // ...
  },

  create ( text ) {
    this._log( `Adding todo: ${text}` );
    // ...
  }
});
```

should really be this:

``` js
var TodoActions = Actions({

  create ( text ) {
    this.log( `Adding todo: ${text}` );
    // ...
  }
}).methods({ log ( msg ) {
    // ...
  }});
```

I'm in favor of bind, but I think it should be behind a flag somehow and not on by default. I have a pretty solid plan of how to implement it internally. 

It should then be exposed as an option in the spec, perhaps `__bindActions: true` ?

Another note: once the action method is created the context cannot be changed as the action creation pulls in the function in the spec using closures. I'm also pretty sure if bind is used on those methods after instantiation things will break. 

I should be able to produce an update in the morning. Its past the witching hour here. Need some Z'sss. 

Let me know you're thoughts.

**Comment by joshdmiller** [comment]
Whassup, @BerkeleyTrue?

I quickly tested it before submitting this last night by changing [this line](https://github.com/ThunderCatsJS/thundercats/blob/master/src/Actions.js#L38) to this:

``` js
value = map.bind(this)(value);
```

And that worked well in my limited attempt (and the unit tests still pass). But I agree with making it optional as I'm not a fan of "voodoo" in libraries.

I'd be happy to submit a PR for this if you're busy. Just let me know!

I suggested the underscore-prefixed method `_log` in the second example I gave because they were already filtered out ([ref](https://github.com/ThunderCatsJS/thundercats/blob/master/src/Actions.js#L18)), so it should be possible to add underscore-prefixed methods to the resulting stamp untouched and the above code would work. That said, calling `methods( ... )` on the resulting stamp would certainly work, but is more verbose (but also ergo more clear).

**Comment by BerkeleyTrue** [comment]
That is strange... I feel like the context should be undefined at that point.

If I walk through this...
<steps through code using dev tools>

Wow, that is strange. The context on that line is the actions object... ok cool. You learn something new every day.

If this ^ is true shouldn't this:

``` js
var Logger = stampit().methods({
  log ( msg ) {
    // ...
  }
});

var TodoActions = Logger.compose(Actions({
  create ( text ) {
    this.log( `Adding todo: ${text}` );
    // ...
  }
}));
```

work as well? The context in action function is the actions object. That means the map function would get its context from the action function which is the stamp instance. @joshdmiller Have you tried the compose function and found it did not work?

**Comment by BerkeleyTrue** [comment]
> I'd be happy to submit a PR for this if you're busy. Just let me know!

That would be great!

**Comment by joshdmiller** [comment]
@BerkeleyTrue Yeah, I tried it, but `this === undefined` without the explicit bind. Here's my thought process: the [action function](https://github.com/ThunderCatsJS/thundercats/blob/master/src/Actions.js#L35) is [mixed into the created stamp](https://github.com/ThunderCatsJS/thundercats/blob/master/src/Actions.js#L93), and therefore it has the context of the stamp when it runs (`this === stamp`). That action method then [calls the passed-around mapping function](https://github.com/ThunderCatsJS/thundercats/blob/master/src/Actions.js#L38), without any context (so `this === undefined`). I think the explicit bind should be necessary.
